const machineData = [
  {
    "machine name": "Auto Winding Machine",
    "machine id": "machine 001",
    "daily energy": "0",
    "monthly energy": "0",
    "yearly energy": "0",
    "active power": "0",
    "aparent power": "0",
    "reactive power": "0",
    "current": "0",
    "voltage": "0",
    "power factor": "0",
    "idle daily": "0",
    "idle monthly": "0",
    "idle yearly": "0",
  },
  {
    "machine name": "Boiler Machine",
    "machine id": "machine 002",
    "daily energy": "0",
    "monthly energy": "0",
    "yearly energy": "0",
    "active power": "0",
    "aparent power": "0",
    "reactive power": "0",
    "current": "0",
    "voltage": "0",
    "power factor": "0",
    "idle daily": "0",
    "idle monthly": "0",
    "idle yearly": "0",
  },
  {
    "machine name": "Dummy Machine",
    "machine id": "machine 003",
    "daily energy": "0",
    "monthly energy": "0",
    "yearly energy": "0",
    "active power": "0",
    "aparent power": "0",
    "reactive power": "0",
    "current": "0",
    "voltage": "0",
    "power factor": "0",
    "idle daily": "0",
    "idle monthly": "0",
    "idle yearly": "0",
  },
];
export default machineData;
